### ISSUE TITLE
Error message: Uncaught TypeError: Argument 1 passed to EventEspresso\Square\api\SquareApi::__construct() must be of the type string, null given

### ISSUE THREAD

**Issue by Pebblo** [eventespresso/eea-square-gateway#16]
Hi Nazar,

A user is reporting this error:

```
Error Details
=============
An error of type E_ERROR was caused in line 69 of the file /home/omnilargess/public_html/wp-content/plugins/eea-square-gateway/api/SquareApi.php. Error message: Uncaught TypeError: Argument 1 passed to EventEspresso\Square\api\SquareApi::__construct() must be of the type string, null given, called in /home/omnilargess/public_html/wp-content/plugins/eea-square-gateway/modules/EED_SquareOnsiteOAuth.module.php on line 598 and defined in /home/omnilargess/public_html/wp-content/plugins/eea-square-gateway/api/SquareApi.php:69
Stack trace:
#0 /home/omnilargess/public_html/wp-content/plugins/eea-square-gateway/modules/EED_SquareOnsiteOAuth.module.php(598): EventEspresso\Square\api\SquareApi->__construct()
#1 /home/omnilargess/public_html/wp-content/plugins/eea-square-gateway/payment_methods/SquareOnsite/forms/SettingsForm.php(234): EED_SquareOnsiteOAuth::getMerchantLocations()
#2 /home/omnilargess/public_html/wp-content/plugins/eea-square-gateway/payment_methods/SquareOnsite/forms/SettingsForm.php(138): EventEspresso\Square\payment_methods\SquareOnsite\forms\SettingsForm->oauthHealthCheck()
#3 /home/omnilargess/public_html/wp-content/plugins/eea-square-gateway/payment_metho
```

**Comment by Pebblo** [comment]
They gave me FTP access so I managed to grab the full stack trace.

```
[25-Nov-2021 15:19:52 UTC] PHP Fatal error:  Uncaught TypeError: Argument 1 passed to EventEspresso\Square\api\SquareApi::__construct() must be of the type string, null given, called in /home/omnilargess/public_html/wp-content/plugins/eea-square-gateway/modules/EED_SquareOnsiteOAuth.module.php on line 598 and defined in /home/omnilargess/public_html/wp-content/plugins/eea-square-gateway/api/SquareApi.php:69
Stack trace:
#0 /home/omnilargess/public_html/wp-content/plugins/eea-square-gateway/modules/EED_SquareOnsiteOAuth.module.php(598): EventEspresso\Square\api\SquareApi->__construct()
#1 /home/omnilargess/public_html/wp-content/plugins/eea-square-gateway/payment_methods/SquareOnsite/forms/SettingsForm.php(234): EED_SquareOnsiteOAuth::getMerchantLocations()
#2 /home/omnilargess/public_html/wp-content/plugins/eea-square-gateway/payment_methods/SquareOnsite/forms/SettingsForm.php(138): EventEspresso\Square\payment_methods\SquareOnsite\forms\SettingsForm->oauthHealthCheck()
#3 /home/omnilargess/public_html/wp-content/plugins/eea-square-gateway/payment_metho in /home/omnilargess/public_html/wp-content/plugins/eea-square-gateway/api/SquareApi.php on line 69
```
