### ISSUE TITLE
Uncaught TypeError: Argument 1 passed to EED_SquareOnsiteOAuth::encryptString() must be of the type string

### ISSUE THREAD

**Issue by lorenzocaum** [eventespresso/eea-square-gateway#27]
Notice: Trying to get property 'nonce' of non-object in /dom16100/wp-content/plugins/eea-square-gateway/modules/EED_SquareOnsiteOAuth.module.php on line 557

Notice: Trying to get property 'application_id' of non-object in /dom16100/wp-content/plugins/eea-square-gateway/modules/EED_SquareOnsiteOAuth.module.php on line 580

Notice: Trying to get property 'access_token' of non-object in /dom16100/wp-content/plugins/eea-square-gateway/modules/EED_SquareOnsiteOAuth.module.php on line 584

Fatal error: Uncaught TypeError: Argument 1 passed to EED_SquareOnsiteOAuth::encryptString() must be of the type string, null given, called in /dom16100/wp-content/plugins/eea-square-gateway/modules/EED_SquareOnsiteOAuth.module.php on line 584 and defined in /dom16100/wp-content/plugins/eea-square-gateway/modules/EED_SquareOnsiteOAuth.module.php:793 Stack trace: #0 /dom16100/wp-content/plugins/eea-square-gateway/modules/EED_SquareOnsiteOAuth.module.php(584): EED_SquareOnsiteOAuth::encryptString(NULL, false) #1 /dom16100/wp-content/plugins/eea-square-gateway/modules/EED_SquareOnsiteOAuth.module.php(743): EED_SquareOnsiteOAuth::refreshToken(Object(EE_Payment_Method)) #2 /dom16100/wp-content/plugins/eea-square-gateway/payment_methods/SquareOnsite/forms/SettingsForm.php(113): EED_SquareOnsiteOAuth::checkAndRefreshToken(Object(EE_Payment_Method)) #3 /dom16100/wp-content/plugins/eea-square-gateway/payment_methods/SquareOnsite/forms/SettingsForm.php(64): EventEspresso\Square\payment_methods\SquareOnsite\forms\SettingsForm->valid in /dom16100/wp-content/plugins/eea-square-gateway/modules/EED_SquareOnsiteOAuth.module.php on line 793

![‹ lorenzochrome21 — Event Smart 2022-01-27 at 3 09 44 PM](https://user-images.githubusercontent.com/1079138/151435929-997b4a9a-50b7-4662-bdc8-dba12099cc92.jpg)

**Steps to reproduce**

Not sure. However, I do remember what I did on the site.

In this issue (https://github.com/eventespresso/eventsmart.com-website/issues/886#issuecomment-1018780369), I noticed that two sites deactivated the Square payment method. On this new site where I reported this issue, I followed these steps:

- Last Friday, Jan 21, I set up a new testing site through Chrome.
- I purchased the Square payment gateway to get access to the upgrade.
- I activated the Square in the payment methods screen.
- Then connected it in live mode.
- After, I set a Slack reminder to check to see if it was deactivated the following Monday.
- On Monday's check, the Square payment method was not deactivated.
- Today is Thursday so almost a week later, I went back to the site to check on the deactivated issue again. This time, I noticed a fatal error.

**Reported or seen on**

https://lorenzochrome21.makeeventsnotwar.com/wp-admin/admin.php?page=espresso_payment_settings#espresso_squareonsite_payment_settings

**Other notes**

I saw the same error on one of my testing sites (https://enzo12staging.wpengine.com/wp-admin/admin.php?page=espresso_payment_settings#espresso_squareonsite_payment_settings):

An error of type E_ERROR was caused in line 793 of the file /nas/content/live/enzo12staging/wp-content/plugins/eea-square-gateway/modules/EED_SquareOnsiteOAuth.module.php. Error message: Uncaught TypeError: Argument 1 passed to EED_SquareOnsiteOAuth::encryptString() must be of the type string, null given, called in /nas/content/live/enzo12staging/wp-content/plugins/eea-square-gateway/modules/EED_SquareOnsiteOAuth.module.php on line 584 and defined in /nas/content/live/enzo12staging/wp-content/plugins/eea-square-gateway/modules/EED_SquareOnsiteOAuth.module.php:793
Stack trace:
#0 /nas/content/live/enzo12staging/wp-content/plugins/eea-square-gateway/modules/EED_SquareOnsiteOAuth.module.php(584): EED_SquareOnsiteOAuth::encryptString(NULL, false)
#1 /nas/content/live/enzo12staging/wp-content/plugins/eea-square-gateway/modules/EED_SquareOnsiteOAuth.module.php(743): EED_SquareOnsiteOAuth::refreshToken(Object(EE_Payment_Method))
#2 /nas/content/live/enzo12staging/wp-content/plugins/eea-square-gateway/payment_methods/SquareOnsite/forms/SettingsForm.php(113): EED_SquareOnsiteOAuth::checkAndRefreshToken(Object(EE_Payment_Method))
#3 /nas/content/live/enzo12staging/wp-content/plugins/eea-square-gateway/

![‹ Lorenzo Caum Site — WordPress 2022-01-27 at 3 30 06 PM](https://user-images.githubusercontent.com/1079138/151438649-4396cb05-2717-4ee6-8b09-3f037cdfeb15.jpg)

Tony shared this feedback in Slack support-desk:

> It means the keys have been set nothing and the pm is trying to use them. So the problem is not the fatal itself.... its that the keys are being blanked

**Comment by lorenzocaum** [comment]
Hey there @knazart I saw Square had a fatal on a testing site on a subsite on MakeEventsNotWar. Tony mentioned it is from the keys for Square being blanked as he has seen this with some Event Espresso customers.

In another conversation, you mentioned issues like this can be tough to debug. I wrote out the steps that I followed to get set up with Square here: 

https://github.com/eventespresso/eea-square-gateway/issues/27#issue-1116697737

I don't understand how the keys are stored but a couple of ideas popped into my head:

- Does Square interact with a transient (temporary storage)?
- Does Square use a cron to check the keys are valid on a schedule? Or when someone browses to the Square payment method screen?

Is there any additional information that you need that would be help to debug this issue?
